#!/usr/bin/env python3
"""
render_report.py — the printable board report (assets/report-layout.md), A4 portrait.

Cover band · executive summary · residual heat map + theme rollup · ranked register
with the appetite cut line · over-appetite focus · risk acceptances · footer stamp.
Print to PDF from the browser (or any HTML→PDF tool) to produce the hand-out.

Board *language* is never invented here. Pass --translations with the output of the
ciso-board-translation skill; without it the narrative slots render as clearly-
labelled placeholders and only the derived figures are shown.

Usage:
  python3 render_report.py <register.rr> [out.html] [--today YYYY-MM-DD]
                           [--translations translations.json]
"""

import sys

import _common as C


def cover(ctx: C.Context) -> str:
    """The cover band. Its date carries `ctx.ZONE`, and the reason is not cosmetic.

    `--today` defaults to the UTC date (see _common._today_utc()), so on the evening of
    2026-07-29 in California this line read "As of 2026-07-30" — tomorrow's date, on the one
    artifact in this skill that gets printed and handed round a table, to a reader who had
    asked for no such thing. The date is right and the reader's reading of it was wrong,
    which is a labelling problem and is fixed by labelling.

    Stamped from `ctx.ZONE` rather than by calling `ctx.as_of_line()`, which is the other
    way to get the label and was rejected. as_of_line() is "As of DATE UTC · compared
    against LABEL" / "· no snapshot yet, so no trend is available" — a trailing snapshot
    clause that this cover ALREADY prints, as the `.snap` badge two lines below, with the
    baseline's own timestamp beside it. Calling it here would state the baseline twice on
    one cover and turn a one-line `.sub` into a wrapped two-clause sentence, which is a
    layout change on a fixed-geometry A4 sheet. Reading ZONE keeps the zone string itself
    in exactly one place, which is the part that could drift.
    """
    sm = ctx.settings
    if ctx.baseline:
        ts = (ctx.baseline.get("ts") or "")[:10]
        stamp = (f'<div class="snap">Compared against {C.esc(ctx.baseline.get("label", "—"))}'
                 f'{" — " + ts if ts else ""}</div>')
    else:
        stamp = '<div class="snap">No prior snapshot — this is the first review point</div>'
    # Disclosed on the cover, not buried later. This artifact gets printed and handed
    # round a table, so a reader must not reach the risk tables before learning that some
    # of them are unreviewed candidates.
    note = C.provisional_note(ctx.live)
    prov = f'<div class="provisional-note">{note}</div>' if note else ""
    return f"""<div class="cover">
  <div class="eyebrow">Cyber Aware Creations · Risk Register</div>
  <h1>{C.esc(ctx.meta.get('clientName') or '(unnamed register)')}</h1>
  <div class="sub">Cybersecurity risk report · Prepared by
    {C.esc(ctx.meta.get('assessor') or '—')} · As of {ctx.today} {ctx.ZONE}<br>
    Appetite: {C.esc(sm['appetite'])} &nbsp;·&nbsp; {sm['matrixSize']}×{sm['matrixSize']} matrix
    &nbsp;·&nbsp; {ctx.live['registerTotal']} risks</div>
  {stamp}{prov}</div>"""


def exec_summary(ctx: C.Context) -> str:
    """Narrative slot, freshness caveat, then the figures.

    `C.freshness_line()` goes on BOTH branches, and this renderer carries it for the same
    reason render_board does — it is the SECOND board-facing artifact, and the one this
    skill's board-safety suite names in its own header: the title guard was written into the
    executive dashboard first and the printable report kept exposing raw framework wording
    for a full release afterwards. A board caveat wired into one of two board pages is that
    mistake in progress. The sentence lives in _common.py precisely so both can call it, and
    the two must never carry different freshness wording over one register.

    Both branches, because a page whose narrative slot is a placeholder is exactly the page
    most likely to be read off the numbers alone, and a report rendered WITH board language
    is the one that reaches a board. Deleting the call from either branch fails a check.

    Filed as a caveat on the figures rather than under "Decisions for the board", which is
    an ask; and placed above the stat grid so it is read before the numbers it qualifies
    rather than after them. This artifact is printed, so a caveat below the fold of a page
    break is a caveat nobody reads.
    """
    s = ctx.live
    fresh = C.freshness_line(ctx)
    if ctx.tr.executive_summary:
        lead = (f'<p class="lead">{C.esc(ctx.tr.executive_summary)}</p>'
                f'<div class="note">Executive narrative generated by the ciso-board-translation '
                f'skill.</div>'
                f'{fresh}')
    else:
        lead = (f'<p class="lead placeholder">{C.PLACEHOLDER}</p>'
                f'<div class="note">Figures below are derived from the register and are complete; '
                f'only the narrative is missing.</div>'
                f'{fresh}')
    if len(ctx.trend) > 1:
        prev = ctx.trend[-2]
        d = s["overAppetite"] - prev["overAppetite"]
        key = "improving" if d < 0 else "worsening" if d > 0 else "steady"
        over = (f'{s["overAppetite"]} <span style="color:{C.VELOCITY_COLOR[key]}">'
                f'{C.VELOCITY_MARK[key]}</span>')
        over_sub = f'Over appetite (was {prev["overAppetite"]} at {C.esc(prev["label"])})'
    else:
        over, over_sub = str(s["overAppetite"]), "Over appetite (no prior snapshot)"
    stats = [(s["registerTotal"], "Total risks tracked"), (over, over_sub),
             (s["closed"], "Closed"),
             (len(ctx.attention["acceptanceDue"]), "Acceptances due for re-validation")]
    grid = "".join(f'<div class="stat"><div class="n">{n}</div><div class="l">{lab}</div></div>'
                   for n, lab in stats)
    pills = "".join(
        f'<div class="bandpill" style="background:{C.BAND[b]};color:{C.BAND_ON[b]}">'
        f'<span class="bn">{s["byBand"][b]}</span>{C.BAND_LABEL[b]}</div>'
        for b in ["low", "medium", "high", "critical"])
    return f'{lead}<div class="grid">{grid}</div><div class="bandrow">{pills}</div>'


def heat(ctx: C.Context) -> str:
    counts, skipped = ctx.heat_counts("residual")
    rows = ""
    for impact in range(ctx.size, 0, -1):
        cells = f'<td class="ax">{impact}</td>'
        for lik in range(1, ctx.size + 1):
            b = C.sr.band(C.sr.exposure(lik, impact), ctx.size)
            n = counts[impact - 1][lik - 1]
            # BAND_MID, not BAND: a matrix cell is a zone, and G.heat_matrix draws the
            # same grid in the same tones on the board page.
            fg = C.BAND_MID_ON[b]
            cells += f'<td style="background:{C.BAND_MID[b]};color:{fg}">{n or ""}</td>'
        rows += f"<tr>{cells}</tr>"
    foot = '<td class="ax"></td>' + "".join(f'<td class="ax">{l}</td>'
                                           for l in range(1, ctx.size + 1))
    note = ""
    if skipped:
        many = skipped > 1
        note = (f'<div class="note">{skipped} risk{"s" if many else ""} scored above the '
                f'{ctx.size}×{ctx.size} matrix and {"are" if many else "is"} not plotted; '
                f'{"they remain" if many else "it remains"} counted in every total.</div>')
    return (f'<div class="tscroll"><table class="heat">{rows}<tr>{foot}</tr>'
            f'</table></div>{note}')


def themes(ctx: C.Context) -> str:
    rows = ""
    for t in ctx.theme_rollup:
        col = C.VELOCITY_COLOR[t["direction"]]
        rows += (f'<tr><td>{C.esc(t["name"])}</td><td>{t["count"]}</td>'
                 f'<td>{C.chip(t["worst"])}</td><td>{t["over"] or "—"}</td>'
                 f'<td style="color:{col};font-weight:700" title="{t["direction"]}">'
                 f'{C.VELOCITY_MARK[t["direction"]]}</td></tr>')
    return rows or '<tr><td colspan="5" class="note">No themes defined.</td></tr>'


def acceptance_flag(r: dict) -> str:
    if r["acceptanceExpired"]:
        return '<span class="fl">past expiry</span>'
    if r["acceptanceDue"]:
        return '<span class="fl">due for re-validation</span>'
    if r["acceptanceIncomplete"]:
        return '<span class="fl">incomplete — no approver or justification</span>'
    return "acceptance current"


def register_table(ctx: C.Context) -> str:
    """One register, sectioned by the decision each risk needs.

    Every risk appears exactly once. What used to be separate over-appetite and
    acceptance tables is now a sub-line on the risk's own row, so the board reads
    each item once, in the group that says what to do with it.
    """
    groups = {"over": [], "acceptedOver": [], "accepted": [], "treated": [], "closed": []}
    for r in ctx.risks:
        if r.get("status") == "closed":
            groups["closed"].append(r)
        elif r["overAppetite"]:
            # Over appetite is not the same question as undecided. A risk the board
            # formally accepted, still current, belongs in its own group — filing it
            # under "board decision needed" made this report contradict its own
            # Decisions section a few pages later.
            #
            # Uses the same predicate as the executive dashboard so the two artifacts
            # cannot disagree about what counts as a live acceptance.
            key = "acceptedOver" if C.Context._accepted_and_current(r) else "over"
            groups[key].append(r)
        elif r["acceptance"]:
            groups["accepted"].append(r)
        else:
            groups["treated"].append(r)
    for g in groups.values():
        g.sort(key=lambda r: -r["residualExposure"])

    def sub_lines(r, group):
        out = ""
        if group in ("over", "acceptedOver"):
            out += (f'<div class="tx">{C.esc(r["translation"])}</div>' if r["translation"]
                    else '<div class="tx placeholder">Business-impact line not supplied — run '
                         'ciso-board-translation.</div>')
            out += (f'<div class="tx"><b>Treatment in place:</b> '
                    f'{C.esc(r["response"].get("description") or "none recorded")}</div>')
        if r["acceptance"]:
            a = r["acceptance"]
            out += (f'<div class="tx"><b>Accepted</b> by '
                    f'{C.esc(a.get("approver") or "— no approver —")} on '
                    f'{C.esc(a.get("acceptedDate") or "—")} · re-validate by '
                    f'{C.esc(a.get("revalidationDate") or "—")}'
                    f'{" · expires " + C.esc(a.get("expiryDate")) if a.get("expiryDate") else ""}'
                    f' — {acceptance_flag(r)}<br>'
                    f'{C.esc(a.get("justification") or "no justification recorded")}</div>')
        return out

    def row(r, group):
        title = C.risk_title(r, bold=(group in ("over", "acceptedOver")))
        vel = ""
        if r["priorExposure"] is not None and r["delta"]:
            vel = (f'<span style="color:{C.VELOCITY_COLOR[r["velocity"]]}">'
                   f'{C.VELOCITY_MARK[r["velocity"]]}</span>')
        flag = ' <span class="fl">⚠</span>' if r["overAppetite"] else ""
        return (f'<tr><td>{r["id"]}</td><td>{title}{sub_lines(r, group)}</td>'
                f'<td>{C.esc(r["themeName"])}</td><td>{r["inherentExposure"]}</td>'
                f'<td>{C.esc(r["response"]["type"])}</td>'
                f'<td>{C.chip(r["residualBand"])} {r["residualExposure"]} {vel}{flag}</td>'
                f'<td>{C.esc(r["owner"] or "— unowned —")}</td>'
                f'<td>{C.esc(r["status"])}</td></tr>')

    appetite = C.BAND_LABEL[ctx.appetite]
    sections = [
        ("over", f"Above the {appetite.lower()} appetite — board decision needed",
         "Each carries its business impact and the treatment in place.", True),
        ("acceptedOver", f"Above the {appetite.lower()} appetite — already accepted, no decision sought",
         "The board has formally accepted these and the acceptance is still current. Listed for "
         "visibility; the renewal date is the only thing that needs watching.", True),
        ("accepted", "Accepted — standing board approval",
         "Within appetite because the residual risk was formally accepted; the acceptance itself "
         "is what needs renewing.", False),
        ("treated", f"Within the {appetite.lower()} appetite — under treatment",
         "Managed at the working level; no board action sought.", False),
        ("closed", "Closed", "Treated out or no longer applicable; retained for the audit trail.",
         False),
    ]
    out = ""
    for key, title, blurb, is_cut in sections:
        rs = groups[key]
        if not rs:
            continue
        cls = "grp cut" if is_cut else "grp"
        out += (f'<tr class="{cls}"><td colspan="8"><span class="cutlabel">{title} — {len(rs)}'
                f'</span><div class="note" style="margin-top:4px">{blurb}</div></td></tr>')
        out += "".join(row(r, key) for r in rs)
    return out


def register_note(ctx: C.Context) -> str:
    """The two things a board notices by their absence."""
    bits = []
    if not ctx.attention["overAppetite"]:
        bits.append(f'No live risk sits above the {C.BAND_LABEL[ctx.appetite].lower()} appetite '
                    f'at this review point.')
    if any(r["acceptance"] for r in ctx.risks):
        bits.append('Recorded acceptance — approver, justification, re-validation and expiry — is '
                    'the audit-defensible layer (DORA RTS (EU) 2024/1774 Art. 3(d); '
                    'NYDFS 23 NYCRR 500). Not legal advice.')
    return " ".join(bits)


def decisions(ctx: C.Context) -> str:
    if not ctx.decisions:
        return ""
    items = "".join(f"<li>{C.esc(d)}</li>" for d in ctx.decisions)
    return f'<h2>Decisions for the board</h2><ul class="dec">{items}</ul>'


def css() -> str:
    """The page stylesheet, built when it is asked for.

    This was a module-level constant, an f-string evaluated at import — which is before
    `_common.apply_brand()` has run, so every colour in it was frozen at the CAC palette and
    a `--brand` override reached the charts while leaving the page around them unbranded.
    Half a client's palette looks like a mistake in a way that none of it does not.
    """
    return f"""
@page{{size:A4;margin:14mm 14mm 20mm}}
*{{box-sizing:border-box}}
body{{margin:0;font-family:'Manrope',system-ui,sans-serif;color:{C.INK};font-size:10.5px}}
h1,h2,h3{{font-family:'Space Grotesk','Manrope',sans-serif;margin:0}}
.cover{{background:{C.INK};color:{C.LIME};padding:26px 28px;border-radius:10px;margin-bottom:22px}}
.eyebrow{{color:{C.PATINA};font-size:11px;letter-spacing:.16em;text-transform:uppercase;
  font-weight:700}}
.cover h1{{font-size:30px;margin:10px 0 6px}}
.cover .sub{{color:{C.LIME_DIM};font-size:12px;line-height:1.6}}
.cover .snap{{margin-top:14px;display:inline-block;background:{C.PATINA};color:{C.INK};
  font-weight:700;border-radius:6px;padding:4px 12px;font-size:11px}}
.provisional-note{{margin-top:14px;border-left:3px solid {C.BAND["high"]};
  background:{C.BAND["high"]}1a;padding:8px 12px;font-size:11px;line-height:1.55}}
h2{{font-size:14px;margin:22px 0 10px;padding-bottom:5px;border-bottom:2px solid {C.INK}}}
.lead{{font-size:12px;line-height:1.6;margin:0}}
.grid{{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:12px 0}}
.stat{{border:1px solid {C.WB_LINE};border-radius:8px;padding:9px 12px}}
.stat .n{{font-family:'Space Grotesk';font-size:20px;font-weight:600}}
.stat .l{{color:{C.SLATE};font-size:10px;line-height:1.35}}
.bandrow{{display:flex;gap:6px;margin:10px 0}}
.bandpill{{flex:1;border-radius:6px;text-align:center;padding:6px;font-size:10px}}
.bandpill .bn{{font-family:'Space Grotesk';font-size:16px;font-weight:600;display:block}}
.row2{{display:flex;gap:20px;align-items:flex-start}}
/* Flex items, like grid items, default to min-width:auto — their min-content — so
   the themes table refused to shrink and pushed the sheet past the viewport. */
.row2>*{{min-width:0}}
table.heat{{border-collapse:collapse}}
table.heat td{{width:30px;height:30px;text-align:center;font-weight:700;font-size:11px;
  border:2px solid #fff}}
table.heat td.ax{{color:{C.SLATE};font-weight:600;font-size:9px;width:auto;height:auto;
  border:none;background:none}}
.axcap{{color:{C.SLATE};font-size:9px;text-transform:uppercase;letter-spacing:.08em}}
table.data{{width:100%;border-collapse:collapse;font-size:9.5px}}
table.data th{{background:{C.INK};color:{C.LIME};text-align:left;padding:6px 7px;font-size:9px;
  font-weight:600}}
table.data td{{padding:5px 7px;border-top:1px solid {C.WB_LINE};vertical-align:top}}
.chip{{border-radius:999px;padding:1px 6px;font-size:8.5px;font-weight:700;white-space:nowrap}}
.fl{{color:{C.BAND['critical']};font-weight:700}}
.tx{{color:{C.SLATE};font-style:italic;font-size:9px;margin-top:2px;line-height:1.4}}
.note{{color:{C.SLATE};font-size:9px;font-style:italic;margin-top:6px}}
/* The freshness sentence is a caveat on the whole document, not a continuation of the
   sidecar attribution note above it, so it takes a rule and a separator. Italic is
   dropped for the same reason as on the executive dashboard: this note is mostly
   numbers, day ranges and risk IDs, and italics make those measurably harder to read —
   more so here at 9px on a sheet that gets printed. Colour and size stay inherited from
   .note deliberately: SLATE on white is the one contrast judgement responsive.sh already
   measures for this file, and a second value here would be a second judgement to keep. */
.note.freshness{{font-style:normal;border-top:1px solid {C.WB_LINE};padding-top:7px;
  margin-top:9px;line-height:1.5}}
.placeholder{{background:repeating-linear-gradient(135deg,#EFEBE0,#EFEBE0 6px,
  #FFFFFF 6px,#FFFFFF 12px);border-radius:4px;padding:3px 6px;display:inline-block;
  color:{C.SLATE}}}
tr.grp td{{border-top:1.5px solid {C.INK};border-bottom:1px solid {C.WB_LINE};
  padding:9px 7px 7px;background:#fff}}
tr.grp.cut td{{border-top:2.5px dashed {C.BAND['critical']}}}
tr.grp .note{{font-style:normal}}
.cutlabel{{display:inline-block;background:{C.INK};color:{C.LIME};font-size:8.5px;font-weight:700;
  padding:3px 12px;border-radius:999px;text-transform:uppercase;letter-spacing:.05em}}
ul.dec{{margin:0;padding-left:16px;font-size:10.5px;line-height:1.6}}
.page{{page-break-before:always}}
.stamp{{position:fixed;bottom:6mm;left:0;right:0;text-align:center;color:{C.SLATE};
  font-size:8px;letter-spacing:.02em}}
@media screen{{
  body{{background:{C.WB};padding:24px}}
  .sheet{{max-width:820px;margin:0 auto;background:#fff;padding:28px 32px;
    border:1px solid {C.WB_LINE};border-radius:10px}}
  .stamp{{position:static;margin-top:24px;padding-top:10px;border-top:1px solid {C.WB_LINE}}}
}}
/* This is a print artifact — an A4 sheet with fixed geometry — but it is *delivered*
   as HTML, so it gets opened on a phone. Everything below is screen-only and cannot
   reach the PDF: @page and the rules above the `@media screen` block govern print.
   The sheet keeps its shape; only the wide tables scroll inside their own box, so
   the page itself never scrolls sideways. */
@media screen and (max-width:860px){{
  body{{padding:10px}}
  .sheet{{max-width:none;padding:18px 16px}}
  /* align-items:flex-start is a cross-axis rule: harmless while the row is
     horizontal, but once stacked it shrink-wraps each item to its content width
     instead of the column, which put the themes table back outside the page. */
  .row2{{flex-direction:column;align-items:stretch}}
  .grid{{grid-template-columns:repeat(2,1fr)}}
  .bandrow{{flex-wrap:wrap}}
  .tscroll{{overflow-x:auto}}
  .tscroll>table.data{{min-width:620px}}
}}
"""


def render(ctx: C.Context) -> str:
    client = C.esc(ctx.meta.get("clientName") or "")
    title_tail = " · " + client if client else ""
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Risk Register — Board Report{title_tail}</title>
{C.fonts(ctx.offline)}<style>{css()}</style></head><body><div class="sheet">
{cover(ctx)}
<h2>Executive summary</h2>
{exec_summary(ctx)}

<div class="row2">
  <div><h2 style="border:none;margin-bottom:4px">Residual heat map</h2>
    <div class="axcap">↑ Impact</div>{heat(ctx)}
    <div class="axcap" style="text-align:right">Likelihood →</div></div>
  <div style="flex:1"><h2 style="border:none;margin-bottom:4px">Risk themes</h2>
    <div class="tscroll"><table class="data"><tr><th>Theme</th><th>Risks</th>
      <th>Worst residual</th><th>Over</th>
      <th>Trend</th></tr>{themes(ctx)}</table></div>
    <div class="note">Trend compares each theme's total residual exposure against
      {C.esc(ctx.baseline.get('label', 'the last snapshot')) if ctx.baseline else 'nothing — no snapshot exists yet'}.</div>
  </div>
</div>

<div class="page"></div>
<h2>Risk register — grouped by the decision needed</h2>
<div class="tscroll"><table class="data"><tr><th>ID</th><th>Risk</th><th>Theme</th>
<th>Inh</th><th>Response</th>
  <th>Residual</th><th>Owner</th><th>Status</th></tr>
{register_table(ctx)}</table></div>
<div class="note">Every risk appears once, in the group that says what the board is being asked to
do with it; within each group, ranked by residual exposure. {register_note(ctx)}</div>

{decisions(ctx)}
<div class="stamp">{C.esc(ctx.footer("board report"))}</div>
</div></body></html>"""


if __name__ == "__main__":
    ctx = C.build(sys.argv[1:], __doc__, "risk-register-board-report.html")
    C.write(ctx, render(ctx))
